# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ENV['SHARED'], "/shared" if ENV['SHARED']

  config.vm.provision "shell", path: "installdeps.sh", privileged: false
end
